# adapted from https://github.com/denoland/std/blob/main/.github/workflows/workspace_publish.yml

name: ci

on:
  push:
    branches:
      - main
      - dev/*
      - chore/*
      - feature/*
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-deno:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest

    steps:
      - name: Set line ending for Windows
        if: matrix.os == 'windows-latest'
        run: git config --global core.autocrlf false

      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: canary

      - name: Install dependencies
        run: deno install

      - name: Format & Check
        run: deno run check

      #      - name: Test
      #        run: deno task test

      - name: Publish dry run
        run: deno publish --dry-run
        if: matrix.os == 'ubuntu-latest'
